// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ3a8cczdo5C6Zos4HSOYw83SO7jXT9Ws',
    appId: '1:212698857200:web:4eb6504b6229fa875ecc35',
    messagingSenderId: '212698857200',
    projectId: 'orange-design-system-6f3f1',
    authDomain: 'orange-design-system-6f3f1.firebaseapp.com',
    storageBucket: 'orange-design-system-6f3f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIY6bMaglXBkcA72v_vja3yI6-7uaR-8U',
    appId: '1:212698857200:android:92978ae61c91c8b85ecc35',
    messagingSenderId: '212698857200',
    projectId: 'orange-design-system-6f3f1',
    storageBucket: 'orange-design-system-6f3f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeQGo-TWlYr2zV-EsORydwijMUz5NIrzg',
    appId: '1:212698857200:ios:65d81b588576928f5ecc35',
    messagingSenderId: '212698857200',
    projectId: 'orange-design-system-6f3f1',
    storageBucket: 'orange-design-system-6f3f1.appspot.com',
    iosClientId: '212698857200-lbjkbnd7ra3isfq2tgjiq65kava294ph.apps.googleusercontent.com',
    iosBundleId: 'com.orange.ods.test.flutterapp',
  );
}
