name: setup
description: Setup environment
runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2

    - name: Generate internationalization files
      shell: bash
      run: |
        cd library
        flutter gen-l10n
