arb-dir: lib/l10n
template-arb-file: ods_flutter_en.arb
output-dir: lib/l10n/gen/
synthetic-package: false
output-localization-file: ods_flutter_app_localizations.dart
# Uncomment this line to find errors in l10n generation
#untranslated-messages-file: l10n_errors.txt
