name: Build

on:
  push:
    branches:
      - main
      - develop
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Run app tests
        shell: bash
        run: |
          cd app
          flutter test

      - name: Run library tests
        shell: bash
        run: |
          cd library
          flutter test

  build-android:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Determine build flavor
        id: determine_flavor
        run: echo "::set-output name=flavor::$(if [[ ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }} ]]; then echo "prod"; else echo "qualif"; fi)"

      - name: Build Android app
        shell: bash
        run: |
          cd app
          flutter build apk --flavor=${{ steps.determine_flavor.outputs.flavor }}
          flutter build appbundle --flavor=${{ steps.determine_flavor.outputs.flavor }}

      - name: Store Android app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-app
          path: |
            app/build/app/outputs/flutter-apk/*.apk
            app/build/app/outputs/bundle/*/*.aab

  build-ios:
    runs-on: macos-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Determine build flavor
        id: determine_flavor
        run: echo "::set-output name=flavor::$(if [[ ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }} ]]; then echo "prod"; else echo "qualif"; fi)"

      - name: Build iOS app
        shell: bash
        run: |
          cd app
          flutter build ios --no-codesign --flavor=${{ steps.determine_flavor.outputs.flavor }}

      - name: Store iOS app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: app/build/ios/iphoneos/Runner.app
