name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Run app tests
        shell: bash
        run: |
          cd app
          flutter test

      - name: Run library tests
        shell: bash
        run: |
          cd library
          flutter test

  build-android:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Build Android app
        shell: bash
        run: |
          cd app
          flutter build apk
          flutter build appbundle

      - name: Store Android app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-app
          path: |
            app/build/app/outputs/flutter-apk/*.apk
            app/build/app/outputs/bundle/*/*.aab

  build-ios:
    runs-on: macos-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Build iOS app
        shell: bash
        run: |
          cd app
          flutter build ios --no-codesign

      - name: Store iOS app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: app/build/ios/iphoneos/Runner.app
