name: Deploy Demo App to GitHub Pages 🚀

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: Generate internationalization files
        run: |
          cd library
          flutter gen-l10n
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          workingDir: app
          baseHref: /ods-flutter/
