name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  run:
    name: Flutter tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: Generate internationalization files
        run: |
          cd library
          flutter gen-l10n
      - name: Run Application tests
        run: |
          cd app
          flutter test
      - name: Run Library tests
        run: |
          cd library
          flutter test
